// Original learning examples authored for KeyLingo. No external corpus.
// [Korean target, English target, category, English aliases, Korean aliases]
export type SeedPair = [string, string, string, string[]?, string[]?];
export const words: SeedPair[] = [
  ['사과','apple','food'], ['물','water','food'], ['빵','bread','food'],
  ['우유','milk','food'], ['밥','rice','food',['cooked rice']], ['달걀','egg','food',[],['계란']],
  ['치즈','cheese','food'], ['커피','coffee','food'], ['차','tea','food'], ['소금','salt','food'],
  ['설탕','sugar','food'], ['국','soup','food'], ['바나나','banana','food'], ['포도','grape','food'],
  ['딸기','strawberry','food'], ['오렌지','orange','food'], ['레몬','lemon','food'], ['고기','meat','food'],
  ['생선','fish','food'], ['닭','chicken','animals'], ['개','dog','animals'], ['고양이','cat','animals'],
  ['새','bird','animals'], ['말','horse','animals'], ['소','cow','animals'], ['돼지','pig','animals'],
  ['토끼','rabbit','animals'], ['곰','bear','animals'], ['여우','fox','animals'], ['사자','lion','animals'],
  ['집','house','home',['home']], ['문','door','home'], ['창문','window','home'], ['의자','chair','home'],
  ['책상','desk','home'], ['침대','bed','home'], ['방','room','home'], ['부엌','kitchen','home',[],['주방']],
  ['책','book','study'], ['연필','pencil','study'], ['종이','paper','study'], ['학교','school','study'],
  ['학생','student','study'], ['선생님','teacher','study'], ['친구','friend','people'], ['가족','family','people'],
  ['엄마','mom','people',['mum','mother'],['어머니']], ['아빠','dad','people',['father'],['아버지']],
  ['아이','child','people',['kid']], ['사람','person','people'], ['하늘','sky','nature'], ['해','sun','nature',[],['태양']],
  ['달','moon','nature'], ['별','star','nature'], ['비','rain','nature'], ['눈','snow','nature'],
  ['바람','wind','nature'], ['구름','cloud','nature'], ['나무','tree','nature'], ['꽃','flower','nature'],
  ['산','mountain','nature'], ['강','river','nature'], ['바다','sea','nature',['ocean']], ['숲','forest','nature'],
  ['길','road','places',['street']], ['공원','park','places'], ['가게','shop','places',['store']], ['병원','hospital','places'],
  ['공항','airport','places'], ['역','station','places'], ['기차','train','travel'], ['버스','bus','travel'],
  ['자전거','bicycle','travel',['bike']], ['자동차','car','travel'], ['배','boat','travel'], ['비행기','airplane','travel',['plane','aeroplane']],
  ['오늘','today','time'], ['내일','tomorrow','time'], ['어제','yesterday','time'], ['아침','morning','time'],
  ['저녁','evening','time'], ['밤','night','time'], ['삶','life','abstract'], ['값','price','shopping'],
  ['과일','fruit','food'], ['귀','ear','body'], ['손','hand','body'], ['발','foot','body'],
  ['입','mouth','body'], ['코','nose','body'], ['색','color','everyday',['colour']], ['옷','clothes','everyday'],
];
export const sentences: SeedPair[] = [
  ['안녕하세요','hello','greetings',['hi']], ['감사합니다','thank you','greetings',['thanks'],['고맙습니다']],
  ['안녕히 가세요','goodbye','greetings',['bye']], ['괜찮아요','it is okay','greetings',["it is ok","it's okay","it's ok"]],
  ['물이 필요해요','i need water','needs'], ['배가 고파요','i am hungry','needs',["i'm hungry"]],
  ['목이 말라요','i am thirsty','needs',["i'm thirsty"]], ['피곤해요','i am tired','needs',["i'm tired"]],
  ['사과를 좋아해요','i like apples','food'], ['커피를 마셔요','i drink coffee','food'],
  ['빵을 먹어요','i eat bread','food'], ['우유가 있어요','i have milk','food'],
  ['오늘은 추워요','it is cold today','weather',["it's cold today"]], ['오늘은 더워요','it is hot today','weather',["it's hot today"]],
  ['비가 와요','it is raining','weather',["it's raining"]], ['하늘이 파래요','the sky is blue','weather'],
  ['학교에 가요','i go to school','daily'], ['집에 있어요','i am at home','daily',["i'm at home"]],
  ['책을 읽어요','i read a book','daily'], ['한국어를 배워요','i learn korean','study',["i am learning korean","i'm learning korean"]],
  ['영어를 배워요','i learn english','study',["i am learning english","i'm learning english"]],
  ['문을 열어 주세요','please open the door','requests'], ['앉아 주세요','please sit down','requests'],
  ['천천히 말해 주세요','please speak slowly','requests'], ['다시 말해 주세요','please say it again','requests'],
  ['이름이 뭐예요','what is your name','questions',["what's your name"]], ['얼마예요','how much is it','questions'],
  ['역이 어디예요','where is the station','questions',["where's the station"]],
  ['내일 만나요','see you tomorrow','greetings'], ['좋은 하루 보내세요','have a nice day','greetings',['have a good day']],
];
