// Generated by scripts/generate-audio.cjs; static requires allow offline Metro bundling.
import type { SoundPack } from "./engine";
export const soundPacks: Record<string, SoundPack> = {
  starter: {
    press: {
      normal: [
        require("../../assets/audio/starter/press/normal_01.wav"),
        require("../../assets/audio/starter/press/normal_02.wav"),
        require("../../assets/audio/starter/press/normal_03.wav"),
        require("../../assets/audio/starter/press/normal_04.wav"),
        require("../../assets/audio/starter/press/normal_05.wav"),
      ],
      space: [require("../../assets/audio/starter/press/space_01.wav")],
      enter: [require("../../assets/audio/starter/press/enter_01.wav")],
      backspace: [
        require("../../assets/audio/starter/press/backspace_01.wav"),
      ],
    },
    release: {
      normal: [require("../../assets/audio/starter/release/normal_01.wav")],
      space: [require("../../assets/audio/starter/release/space_01.wav")],
      enter: [require("../../assets/audio/starter/release/enter_01.wav")],
      backspace: [
        require("../../assets/audio/starter/release/backspace_01.wav"),
      ],
    },
  },
  clicky: {
    press: {
    normal: [
      require("../../assets/audio/clicky/normal_01.wav"),
      require("../../assets/audio/clicky/normal_02.wav"),
      require("../../assets/audio/clicky/normal_03.wav"),
      require("../../assets/audio/clicky/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/clicky/space_01.wav"),
      require("../../assets/audio/clicky/space_02.wav"),
    ],
    enter: [require("../../assets/audio/clicky/enter.wav")],
      backspace: [require("../../assets/audio/clicky/backspace.wav")],
    },
    release: {},
  },
  creamy: {
    press: {
    normal: [
      require("../../assets/audio/creamy/normal_01.wav"),
      require("../../assets/audio/creamy/normal_02.wav"),
      require("../../assets/audio/creamy/normal_03.wav"),
      require("../../assets/audio/creamy/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/creamy/space_01.wav"),
      require("../../assets/audio/creamy/space_02.wav"),
    ],
    enter: [require("../../assets/audio/creamy/enter.wav")],
      backspace: [require("../../assets/audio/creamy/backspace.wav")],
    },
    release: {},
  },
  thock: {
    press: {
    normal: [
      require("../../assets/audio/thock/normal_01.wav"),
      require("../../assets/audio/thock/normal_02.wav"),
      require("../../assets/audio/thock/normal_03.wav"),
      require("../../assets/audio/thock/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/thock/space_01.wav"),
      require("../../assets/audio/thock/space_02.wav"),
    ],
    enter: [require("../../assets/audio/thock/enter.wav")],
      backspace: [require("../../assets/audio/thock/backspace.wav")],
    },
    release: {},
  },
  retro: {
    press: {
    normal: [
      require("../../assets/audio/retro/normal_01.wav"),
      require("../../assets/audio/retro/normal_02.wav"),
      require("../../assets/audio/retro/normal_03.wav"),
      require("../../assets/audio/retro/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/retro/space_01.wav"),
      require("../../assets/audio/retro/space_02.wav"),
    ],
    enter: [require("../../assets/audio/retro/enter.wav")],
      backspace: [require("../../assets/audio/retro/backspace.wav")],
    },
    release: {},
  },
  silent: {
    press: {
    normal: [
      require("../../assets/audio/silent/normal_01.wav"),
      require("../../assets/audio/silent/normal_02.wav"),
      require("../../assets/audio/silent/normal_03.wav"),
      require("../../assets/audio/silent/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/silent/space_01.wav"),
      require("../../assets/audio/silent/space_02.wav"),
    ],
    enter: [require("../../assets/audio/silent/enter.wav")],
      backspace: [require("../../assets/audio/silent/backspace.wav")],
    },
    release: {},
  },
  sky: {
    press: {
    normal: [
      require("../../assets/audio/sky/normal_01.wav"),
      require("../../assets/audio/sky/normal_02.wav"),
      require("../../assets/audio/sky/normal_03.wav"),
      require("../../assets/audio/sky/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/sky/space_01.wav"),
      require("../../assets/audio/sky/space_02.wav"),
    ],
    enter: [require("../../assets/audio/sky/enter.wav")],
      backspace: [require("../../assets/audio/sky/backspace.wav")],
    },
    release: {},
  },
  midnight: {
    press: {
    normal: [
      require("../../assets/audio/midnight/normal_01.wav"),
      require("../../assets/audio/midnight/normal_02.wav"),
      require("../../assets/audio/midnight/normal_03.wav"),
      require("../../assets/audio/midnight/normal_04.wav"),
    ],
    space: [
      require("../../assets/audio/midnight/space_01.wav"),
      require("../../assets/audio/midnight/space_02.wav"),
    ],
    enter: [require("../../assets/audio/midnight/enter.wav")],
      backspace: [require("../../assets/audio/midnight/backspace.wav")],
    },
    release: {},
  },
};
