// Static requires keep every selected recording available in offline Metro bundles.
import type { SoundPack } from "./engine";

const physicalPack = (
  normalPress: readonly number[],
  spacePress: number,
  enterPress: number,
  backspacePress: number,
  normalRelease: number,
  spaceRelease: number,
  enterRelease: number,
  backspaceRelease: number,
): SoundPack => ({
  press: {
    normal: normalPress,
    space: [spacePress],
    enter: [enterPress],
    backspace: [backspacePress],
  },
  release: {
    normal: [normalRelease],
    space: [spaceRelease],
    enter: [enterRelease],
    backspace: [backspaceRelease],
  },
});

export const soundPacks: Record<string, SoundPack> = {
  starter: physicalPack(
    [
      require("../../assets/audio/starter/press/normal_01.wav"),
      require("../../assets/audio/starter/press/normal_02.wav"),
      require("../../assets/audio/starter/press/normal_03.wav"),
      require("../../assets/audio/starter/press/normal_04.wav"),
      require("../../assets/audio/starter/press/normal_05.wav"),
    ],
    require("../../assets/audio/starter/press/space_01.wav"),
    require("../../assets/audio/starter/press/enter_01.wav"),
    require("../../assets/audio/starter/press/backspace_01.wav"),
    require("../../assets/audio/starter/release/normal_01.wav"),
    require("../../assets/audio/starter/release/space_01.wav"),
    require("../../assets/audio/starter/release/enter_01.wav"),
    require("../../assets/audio/starter/release/backspace_01.wav"),
  ),
  clicky: physicalPack(
    [
      require("../../assets/audio/clicky/press/normal_01.wav"),
      require("../../assets/audio/clicky/press/normal_02.wav"),
      require("../../assets/audio/clicky/press/normal_03.wav"),
      require("../../assets/audio/clicky/press/normal_04.wav"),
      require("../../assets/audio/clicky/press/normal_05.wav"),
    ],
    require("../../assets/audio/clicky/press/space_01.wav"),
    require("../../assets/audio/clicky/press/enter_01.wav"),
    require("../../assets/audio/clicky/press/backspace_01.wav"),
    require("../../assets/audio/clicky/release/normal_01.wav"),
    require("../../assets/audio/clicky/release/space_01.wav"),
    require("../../assets/audio/clicky/release/enter_01.wav"),
    require("../../assets/audio/clicky/release/backspace_01.wav"),
  ),
  creamy: physicalPack(
    [
      require("../../assets/audio/creamy/press/normal_01.wav"),
      require("../../assets/audio/creamy/press/normal_02.wav"),
      require("../../assets/audio/creamy/press/normal_03.wav"),
      require("../../assets/audio/creamy/press/normal_04.wav"),
      require("../../assets/audio/creamy/press/normal_05.wav"),
    ],
    require("../../assets/audio/creamy/press/space_01.wav"),
    require("../../assets/audio/creamy/press/enter_01.wav"),
    require("../../assets/audio/creamy/press/backspace_01.wav"),
    require("../../assets/audio/creamy/release/normal_01.wav"),
    require("../../assets/audio/creamy/release/space_01.wav"),
    require("../../assets/audio/creamy/release/enter_01.wav"),
    require("../../assets/audio/creamy/release/backspace_01.wav"),
  ),
  thock: physicalPack(
    [
      require("../../assets/audio/thock/press/normal_01.wav"),
      require("../../assets/audio/thock/press/normal_02.wav"),
      require("../../assets/audio/thock/press/normal_03.wav"),
      require("../../assets/audio/thock/press/normal_04.wav"),
      require("../../assets/audio/thock/press/normal_05.wav"),
    ],
    require("../../assets/audio/thock/press/space_01.wav"),
    require("../../assets/audio/thock/press/enter_01.wav"),
    require("../../assets/audio/thock/press/backspace_01.wav"),
    require("../../assets/audio/thock/release/normal_01.wav"),
    require("../../assets/audio/thock/release/space_01.wav"),
    require("../../assets/audio/thock/release/enter_01.wav"),
    require("../../assets/audio/thock/release/backspace_01.wav"),
  ),
  retro: physicalPack(
    [
      require("../../assets/audio/retro/press/normal_01.wav"),
      require("../../assets/audio/retro/press/normal_02.wav"),
      require("../../assets/audio/retro/press/normal_03.wav"),
      require("../../assets/audio/retro/press/normal_04.wav"),
      require("../../assets/audio/retro/press/normal_05.wav"),
    ],
    require("../../assets/audio/retro/press/space_01.wav"),
    require("../../assets/audio/retro/press/enter_01.wav"),
    require("../../assets/audio/retro/press/backspace_01.wav"),
    require("../../assets/audio/retro/release/normal_01.wav"),
    require("../../assets/audio/retro/release/space_01.wav"),
    require("../../assets/audio/retro/release/enter_01.wav"),
    require("../../assets/audio/retro/release/backspace_01.wav"),
  ),
  silent: {
    press: {
      normal: [
        require("../../assets/audio/silent/normal_01.wav"),
        require("../../assets/audio/silent/normal_02.wav"),
        require("../../assets/audio/silent/normal_03.wav"),
        require("../../assets/audio/silent/normal_04.wav"),
      ],
      space: [
        require("../../assets/audio/silent/space_01.wav"),
        require("../../assets/audio/silent/space_02.wav"),
      ],
      enter: [require("../../assets/audio/silent/enter.wav")],
      backspace: [require("../../assets/audio/silent/backspace.wav")],
    },
    release: {},
  },
  sky: physicalPack(
    [
      require("../../assets/audio/sky/press/normal_01.wav"),
      require("../../assets/audio/sky/press/normal_02.wav"),
      require("../../assets/audio/sky/press/normal_03.wav"),
      require("../../assets/audio/sky/press/normal_04.wav"),
      require("../../assets/audio/sky/press/normal_05.wav"),
    ],
    require("../../assets/audio/sky/press/space_01.wav"),
    require("../../assets/audio/sky/press/enter_01.wav"),
    require("../../assets/audio/sky/press/backspace_01.wav"),
    require("../../assets/audio/sky/release/normal_01.wav"),
    require("../../assets/audio/sky/release/space_01.wav"),
    require("../../assets/audio/sky/release/enter_01.wav"),
    require("../../assets/audio/sky/release/backspace_01.wav"),
  ),
  midnight: physicalPack(
    [
      require("../../assets/audio/midnight/press/normal_01.wav"),
      require("../../assets/audio/midnight/press/normal_02.wav"),
      require("../../assets/audio/midnight/press/normal_03.wav"),
      require("../../assets/audio/midnight/press/normal_04.wav"),
      require("../../assets/audio/midnight/press/normal_05.wav"),
    ],
    require("../../assets/audio/midnight/press/space_01.wav"),
    require("../../assets/audio/midnight/press/enter_01.wav"),
    require("../../assets/audio/midnight/press/backspace_01.wav"),
    require("../../assets/audio/midnight/release/normal_01.wav"),
    require("../../assets/audio/midnight/release/space_01.wav"),
    require("../../assets/audio/midnight/release/enter_01.wav"),
    require("../../assets/audio/midnight/release/backspace_01.wav"),
  ),
};
