/* global __dirname, Buffer */
/* Original procedural keyboard foley. No recordings or third-party source assets. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const sampleRate = 44100;
const themes = {
  starter: { fundamental: 440, click: 0.35, tail: 0.022, gain: 0.65 },
  clicky: { fundamental: 1150, click: 0.9, tail: 0.016, gain: 0.63 },
  creamy: { fundamental: 290, click: 0.13, tail: 0.034, gain: 0.7 },
  thock: { fundamental: 160, click: 0.21, tail: 0.049, gain: 0.78 },
  retro: { fundamental: 710, click: 0.67, tail: 0.037, gain: 0.56 },
  silent: { fundamental: 200, click: 0.06, tail: 0.013, gain: 0.21 },
  sky: { fundamental: 560, click: 0.26, tail: 0.032, gain: 0.63 },
  midnight: { fundamental: 220, click: 0.16, tail: 0.043, gain: 0.67 },
};
const samples = ['normal_01', 'normal_02', 'normal_03', 'normal_04', 'space_01', 'space_02', 'enter', 'backspace'];
let seed = 97531;
function random() { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 4294967296; }
function makeWav(profile, category, variant) {
  const length = Math.ceil(sampleRate * 0.19);
  const buffer = Buffer.alloc(44 + length * 2);
  buffer.write('RIFF'); buffer.writeUInt32LE(buffer.length - 8, 4); buffer.write('WAVEfmt ', 8);
  buffer.writeUInt32LE(16, 16); buffer.writeUInt16LE(1, 20); buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(sampleRate, 24); buffer.writeUInt32LE(sampleRate * 2, 28);
  buffer.writeUInt16LE(2, 32); buffer.writeUInt16LE(16, 34); buffer.write('data', 36); buffer.writeUInt32LE(length * 2, 40);
  const pitch = profile.fundamental * (category === 'space' ? 0.72 : category === 'enter' ? 0.84 : category === 'backspace' ? 1.13 : 1) * (0.94 + variant * 0.035);
  const tail = profile.tail * (category === 'space' ? 1.3 : 1);
  let lowNoise = 0;
  for (let i = 0; i < length; i++) {
    const t = i / sampleRate;
    const noise = random() * 2 - 1;
    lowNoise += 0.16 * (noise - lowNoise);
    const attack = Math.min(1, t / 0.001);
    const impact = (Math.sin(2 * Math.PI * pitch * t) * 0.50 + Math.sin(2 * Math.PI * pitch * 2.67 * t) * 0.16 + lowNoise * 0.8) * Math.exp(-t / tail);
    const click = noise * profile.click * Math.exp(-t / 0.0027);
    const releaseT = t - 0.028;
    const release = releaseT > 0 ? Math.sin(2 * Math.PI * pitch * 1.3 * releaseT) * Math.exp(-releaseT / 0.011) * 0.13 : 0;
    const fade = Math.min(1, (length - i) / 220);
    const value = Math.tanh((impact + click + release) * attack * profile.gain) * fade;
    buffer.writeInt16LE(Math.round(value * 28000), 44 + i * 2);
  }
  return buffer;
}
for (const [theme, profile] of Object.entries(themes)) {
  const directory = path.join(root, 'assets', 'audio', theme);
  fs.mkdirSync(directory, { recursive: true });
  samples.forEach((sample, i) => fs.writeFileSync(path.join(directory, `${sample}.wav`), makeWav(profile, sample.split('_')[0], i % 4)));
}
const entries = Object.keys(themes).map(theme => {
  const asset = sample => `require('../../assets/audio/${theme}/${sample}.wav')`;
  return `  ${theme}: { normal: [${samples.slice(0, 4).map(asset).join(', ')}], space: [${samples.slice(4, 6).map(asset).join(', ')}], enter: [${asset('enter')}], backspace: [${asset('backspace')}] }`;
});
fs.mkdirSync(path.join(root, 'src', 'audio'), { recursive: true });
fs.writeFileSync(path.join(root, 'src', 'audio', 'packs.ts'), `// Generated by scripts/generate-audio.cjs; static requires allow offline Metro bundling.\nimport type { SoundPack } from './engine';\nexport const soundPacks: Record<string, SoundPack> = {\n${entries.join(',\n')}\n};\n`);
console.log(`Generated ${Object.keys(themes).length * samples.length} original PCM WAV samples.`);
