import { createInstance } from "i18next";
import { initReactI18next } from "react-i18next";
const i18n = createInstance();
const en = {
  tagline: "A little practice. A satisfying rhythm.",
  languageTitle: "Make yourself at home.",
  languageBody: "Choose your interface language.",
  continue: "Continue",
  studyTitle: "What will you type?",
  studyBody: "Start with three little words.",
  english: "English",
  korean: "Korean",
  home: "Home",
  collection: "Keyboards",
  settings: "Settings",
  learn: "Learn",
  review: "Recall",
  speed: "Speed",
  rain: "Word Rain",
  guided: "Guided",
  tutorial: "First rhythm",
  promptLabel: "TYPE THE MEANING",
  ghostHelp: "Follow the letters. Find your rhythm.",
  recallHelp: "Bring it back from memory.",
  submit: "Check answer",
  hint: "A little hint",
  next: "Next word",
  finish: "See results",
  correct: "Nicely done",
  correction: "Keep this one in mind",
  result: "Practice, made progress.",
  resultBody: "Every little session adds up.",
  tokens: "Tokens",
  accuracy: "Accuracy",
  combo: "Combo",
  time: "Time",
  back: "Back",
  start: "Start typing",
  today: "YOUR DAILY RHYTHM",
  daily: "Daily goal",
  minutes: "min",
  streak: "day streak",
  level: "Level",
  due: "ready to review",
  continueLearning: "Find your rhythm",
  homeBody: "A few words. A clearer mind.",
  learnBody: "Meet a word, one key at a time.",
  reviewBody: "See what you remember.",
  speedBody: "Recall it. Type it. Beat your best.",
  rainBody: "A 60-second shower of words.",
  lockedMode: "Practice Recall first to unlock these words.",
  noDue: "All caught up. Try Learn to meet more words.",
  sound: "Keyboard sound",
  volume: "Volume",
  haptics: "Haptic feedback",
  effects: "Reduced effects",
  goal: "Your daily goal",
  reminder: "Daily reminder",
  schedule: "Schedule reminder",
  cancelReminder: "Turn off reminder",
  reminderDenied: "Reminders unavailable or permission declined.",
  saved: "Saved",
  equipped: "Equipped",
  equip: "Use this keyboard",
  unlock: "Unlock",
  preview: "Try the sound",
  locked: "Keep practicing to unlock",
  owned: "In your collection",
  shopBody: "Find a keyboard that feels like you.",
  practice: "Keep practicing",
  firstCollection: "Meet your first keyboard",
  rewardAd: "Optional reward · +10 Tokens",
  adLimit: "Daily reward limit reached.",
  adFailed: "No reward this time. You can keep practicing.",
  mockLabel: "Development demo · no real charge or ad",
  starterPack: "Starter Pack",
  restore: "Restore purchases",
  unavailable: "Store is not configured yet.",
  purchaseDone: "Starter Pack added to your collection.",
  rainEmpty: "Complete more Recall practice to add words here.",
  exit: "Leave practice",
  exitBody: "This session has not been completed.",
  stay: "Keep typing",
  leave: "Leave",
  notEnough: "Not enough Tokens or level too low.",
  best: "Personal best",
  newBest: "A new personal best",
  soundOff: "Sound off",
  paused: "Paused",
  resume: "Resume",
  goalBody: "Build a habit at your own pace.",
  onboardingDone: "Your rhythm starts here.",
  answerPlaceholder: "Your answer",
  space: "Space",
  delete: "Backspace",
  shift: "Shift",
  previewHint: "Tap any key to listen.",
  loading: "Preparing your keyboard…",
  loadError: "Your progress could not be loaded.",
  retry: "Try again",
  storageError:
    "Progress could not be saved. Please keep the app open and try again.",
  studyLanguage: "Study language",
  uiLanguage: "Interface language",
  notificationHint: "Permission is requested only when you schedule.",
  answer: "Answer",
  words: "words",
  rank: "Rank",
  hintUsed: "Hint used · reduced reward",
  goalComplete: "Daily goal complete",
  previewContinue: "Make it a daily rhythm",
  rainStart: "Start 60-second round",
  completed: "Completed",
  seconds: "s",
  firstKey: "Tap a key to begin",
  sentence: "Short sentences",
  vocabulary: "Words",
  noWords: "Learn a few words first.",
  reset: "Start a fresh practice",
  reminderTime: "Reminder time",
  active: "Active practice",
  select: "Select",
  score: "Score",
  rainInstructions: "Type the meaning of a falling word.",
  dailyLater: "Set your goal in Settings whenever you are ready.",
  freeze: "Streak freezes",
  progress: "Progress",
  reminderOn: "Reminder scheduled",
  saving: "Saving…",
  audioCredits: "Audio credits",
  audioCreditsTitle: "The recordings behind every switch.",
  audioCreditsBody:
    "These physical keyboard samples are bundled for offline play under their original licenses.",
  audioLegacyNote:
    "Quiet Cloud currently uses the original KeyLingo sound while we source a cleared damped recording.",
};
const ko: Record<keyof typeof en, string> = {
  tagline: "짧은 연습, 기분 좋은 리듬.",
  languageTitle: "편한 언어로 시작해요.",
  languageBody: "앱에서 사용할 언어를 골라 주세요.",
  continue: "계속",
  studyTitle: "어떤 언어를 연습할까요?",
  studyBody: "세 단어로 가볍게 시작해요.",
  english: "영어",
  korean: "한국어",
  home: "홈",
  collection: "키보드",
  settings: "설정",
  learn: "배우기",
  review: "기억하기",
  speed: "스피드",
  rain: "단어 비",
  guided: "따라 쓰기",
  tutorial: "첫 번째 리듬",
  promptLabel: "뜻을 보고 입력하세요",
  ghostHelp: "흐린 글자를 따라 리듬을 찾아보세요.",
  recallHelp: "기억 속 단어를 꺼내 보세요.",
  submit: "정답 확인",
  hint: "작은 힌트",
  next: "다음 단어",
  finish: "결과 보기",
  correct: "잘했어요",
  correction: "이 단어를 기억해요",
  result: "차곡차곡 쌓이는 실력.",
  resultBody: "짧은 연습도 분명한 한 걸음이에요.",
  tokens: "토큰",
  accuracy: "정확도",
  combo: "콤보",
  time: "시간",
  back: "뒤로",
  start: "타이핑 시작",
  today: "오늘의 작은 리듬",
  daily: "하루 목표",
  minutes: "분",
  streak: "일 연속",
  level: "레벨",
  due: "개 복습할 단어",
  continueLearning: "나만의 리듬 찾기",
  homeBody: "몇 단어로 가벼워지는 하루.",
  learnBody: "한 글자씩 새로운 단어를 만나요.",
  reviewBody: "얼마나 기억하는지 확인해요.",
  speedBody: "떠올리고, 입력하고, 기록을 넘어요.",
  rainBody: "60초 동안 쏟아지는 단어들.",
  lockedMode: "기억하기를 연습하면 단어가 열려요.",
  noDue: "복습 완료! 배우기에서 새 단어를 만나세요.",
  sound: "키보드 소리",
  volume: "음량",
  haptics: "진동 피드백",
  effects: "효과 줄이기",
  goal: "나에게 맞는 하루 목표",
  reminder: "매일 알림",
  schedule: "알림 예약",
  cancelReminder: "알림 끄기",
  reminderDenied: "알림을 지원하지 않거나 권한이 거절됐어요.",
  saved: "저장했어요",
  equipped: "사용 중",
  equip: "이 키보드 사용",
  unlock: "잠금 해제",
  preview: "소리 들어보기",
  locked: "연습하며 잠금을 풀어 보세요",
  owned: "내 컬렉션",
  shopBody: "내 손에 맞는 기분 좋은 키보드.",
  practice: "계속 연습하기",
  firstCollection: "첫 키보드를 만나보세요",
  rewardAd: "선택 보상 · 10 토큰",
  adLimit: "오늘의 보상을 모두 받았어요.",
  adFailed: "보상을 받지 못했어요. 연습은 계속할 수 있어요.",
  mockLabel: "개발 데모 · 실제 결제·광고 없음",
  starterPack: "스타터 팩",
  restore: "구매 복원",
  unavailable: "아직 스토어가 연결되지 않았어요.",
  purchaseDone: "스타터 팩이 추가됐어요.",
  rainEmpty: "기억하기를 더 연습하면 단어가 추가돼요.",
  exit: "연습을 나갈까요?",
  exitBody: "아직 이번 연습을 마치지 않았어요.",
  stay: "계속 입력",
  leave: "나가기",
  notEnough: "토큰이나 레벨이 부족해요.",
  best: "최고 기록",
  newBest: "새로운 최고 기록",
  soundOff: "소리 꺼짐",
  paused: "잠시 멈춤",
  resume: "계속하기",
  goalBody: "나만의 속도로 습관을 만들어요.",
  onboardingDone: "나만의 리듬이 시작돼요.",
  answerPlaceholder: "정답 입력",
  space: "띄어쓰기",
  delete: "지우기",
  shift: "쌍자음",
  previewHint: "키를 눌러 소리를 들어보세요.",
  loading: "키보드를 준비하고 있어요…",
  loadError: "진행 상황을 불러오지 못했어요.",
  retry: "다시 시도",
  storageError: "저장하지 못했어요. 앱을 닫지 말고 다시 시도해 주세요.",
  studyLanguage: "학습 언어",
  uiLanguage: "앱 언어",
  notificationHint: "예약할 때만 알림 권한을 요청해요.",
  answer: "정답",
  words: "단어",
  rank: "등급",
  hintUsed: "힌트 사용 · 보상 감소",
  goalComplete: "하루 목표 달성",
  previewContinue: "매일의 리듬으로",
  rainStart: "60초 연습 시작",
  completed: "완료",
  seconds: "초",
  firstKey: "키를 눌러 시작하세요",
  sentence: "짧은 문장",
  vocabulary: "단어",
  noWords: "먼저 단어를 배워 보세요.",
  reset: "새 연습 시작",
  reminderTime: "알림 시간",
  active: "실제 연습",
  select: "선택",
  score: "점수",
  rainInstructions: "떨어지는 단어의 뜻을 입력하세요.",
  dailyLater: "설정에서 하루 목표를 정할 수 있어요.",
  freeze: "연속 기록 보호",
  progress: "진행 상황",
  reminderOn: "알림 예약 완료",
  saving: "저장 중…",
  audioCredits: "오디오 크레딧",
  audioCreditsTitle: "각 키보드 축의 실제 녹음 출처",
  audioCreditsBody:
    "실제 키보드 샘플은 원본 라이선스와 함께 앱에 포함되어 오프라인으로 재생돼요.",
  audioLegacyNote:
    "Quiet Cloud는 라이선스가 확인된 저소음 녹음을 확보할 때까지 기존 KeyLingo 소리를 사용해요.",
};
void i18n.use(initReactI18next).init({
  resources: { en: { translation: en }, ko: { translation: ko } },
  lng: "en",
  fallbackLng: "en",
  interpolation: { escapeValue: false },
  initAsync: false,
});
export default i18n;
