export const redesignEn = {
  play: "Play",
  journal: "Progress",
  playground: "YOUR TYPING PLAYGROUND",
  homeTitle: "A little language.\nA lot of feeling.",
  homeSubtitle: "Settle in. Your next few words are waiting.",
  nextRecall: "A few familiar words, ready to return.",
  nextLearn: "Meet something new, one key at a time.",
  yourKeyboard: "ON YOUR DESK",
  todaySession: "TODAY’S SESSION",
  explore: "Explore keyboards",
  playTitle: "Find your flow.",
  playSubtitle: "A quiet practice or a little friendly pressure.",
  learning: "Learning",
  learningIntro: "Make a new language feel familiar.",
  learningDetail: "Follow the letters, then bring them back from memory.",
  arcade: "Arcade",
  arcadeIntro: "Put your rhythm to the test.",
  arcadeDetail: "Recall under pressure. Chase your own best.",
  learningTitle: "One word closer.",
  chooseFormat: "WHAT WILL YOU PRACTICE?",
  chooseMode: "CHOOSE YOUR PRACTICE",
  arcadeTitle: "A little more tempo.",
  arcadeNote:
    "Play with words you already know. Keyboards never change your score.",
  available: "Ready to play",
  needsLearning: "Learn words first to try Recall.",
  needsRecall: "Complete Recall to bring words into the arcade.",
  goLearn: "Go to learning",
  untimed: "At your pace",
  timed: "Against the clock",
  showroom: "THE KEYBOARD COLLECTION",
  collectionTitle: "Find your kind\nof click.",
  collectionSubtitle:
    "Different sounds. Different textures. All yours to discover.",
  allBoards: "All keyboards",
  myBoards: "My collection",
  edition: "KEYBOARD",
  details: "Explore & listen",
  emptyCollection: "Your next keyboard is waiting in the gallery.",
  backCollection: "Back to keyboards",
  soundStudio: "SOUND STUDIO",
  tryBoard: "Make some noise.",
  glideHint: "Tap or glide across the keys. Find your rhythm.",
  cosmetic: "A new feel. The same fair game.",
  cost: "Collection price",
  requiredLevel: "Required level",
  balance: "Your balance",
  needTokens: "{{count}} more Tokens needed",
  needLevel: "Reach level {{level}} to unlock",
  enableSound: "Turn sound on",
  detailUnavailable: "This keyboard is not in the collection.",
  journalTitle: "Small sessions.\nLasting rhythm.",
  recentSessions: "RECENT SESSIONS",
  noSessions: "Your first session is the start of something.",
  sessionCount: "Sessions",
  studyTime: "Today’s practice",
  yourRhythm: "YOUR RHYTHM",
  preferences: "Make it yours",
  progressIntro: "A little each day makes a difference.",
  collectionReward: "Put your progress on your desk.",
  audioCredits: "Audio credits",
  audioCreditsTitle: "The recordings behind every switch.",
  audioCreditsBody:
    "These physical keyboard samples are bundled for offline play under their original licenses.",
  audioLegacyNote:
    "Quiet Cloud currently uses the original KeyLingo sound while we source a cleared damped recording.",
};
export const redesignKo: Record<keyof typeof redesignEn, string> = {
  play: "플레이",
  journal: "기록",
  playground: "나만의 타이핑 플레이그라운드",
  homeTitle: "언어는 조금씩,\n손끝은 기분 좋게.",
  homeSubtitle: "가볍게 앉아, 몇 단어로 시작해요.",
  nextRecall: "익숙한 단어를 다시 꺼낼 시간이에요.",
  nextLearn: "한 글자씩 새로운 단어를 만나요.",
  yourKeyboard: "지금 내 책상 위",
  todaySession: "오늘의 연습",
  explore: "키보드 둘러보기",
  playTitle: "나만의 흐름으로.",
  playSubtitle: "차분하게 익히거나, 조금 더 빠르게 즐기거나.",
  learning: "학습",
  learningIntro: "낯선 언어가 익숙해지는 시간.",
  learningDetail: "글자를 따라 쓰고, 기억 속에서 다시 꺼내 보세요.",
  arcade: "아케이드",
  arcadeIntro: "손끝의 리듬을 시험해 보세요.",
  arcadeDetail: "기억한 단어로 나의 기록에 도전해요.",
  learningTitle: "한 단어만큼 가까이.",
  chooseFormat: "무엇을 연습할까요?",
  chooseMode: "어떻게 연습할까요?",
  arcadeTitle: "템포를 조금 올려요.",
  arcadeNote: "익힌 단어로 즐겨요. 키보드는 점수에 영향을 주지 않아요.",
  available: "플레이 가능",
  needsLearning: "단어를 먼저 배우면 기억하기를 시작할 수 있어요.",
  needsRecall: "기억하기를 마치면 아케이드에서 즐길 단어가 열려요.",
  goLearn: "학습하러 가기",
  untimed: "내 속도대로",
  timed: "시간에 도전",
  showroom: "키보드 컬렉션",
  collectionTitle: "내 취향의\n소리를 찾다.",
  collectionSubtitle: "다른 소리, 다른 질감. 하나씩 발견하는 즐거움.",
  allBoards: "모든 키보드",
  myBoards: "내 컬렉션",
  edition: "키보드",
  details: "자세히 · 소리 체험",
  emptyCollection: "갤러리에서 다음 키보드를 만나 보세요.",
  backCollection: "키보드로 돌아가기",
  soundStudio: "사운드 스튜디오",
  tryBoard: "손끝으로 들어보세요.",
  glideHint: "키를 누르거나 쓸어 보세요. 나만의 리듬으로.",
  cosmetic: "새로운 감각, 변함없는 공정함.",
  cost: "컬렉션 가격",
  requiredLevel: "필요 레벨",
  balance: "보유 토큰",
  needTokens: "토큰 {{count}}개가 더 필요해요",
  needLevel: "레벨 {{level}}에 열려요",
  enableSound: "소리 켜기",
  detailUnavailable: "컬렉션에 없는 키보드예요.",
  journalTitle: "짧은 연습이\n오래가는 리듬으로.",
  recentSessions: "최근 연습",
  noSessions: "첫 연습부터 기록이 쌓이기 시작해요.",
  sessionCount: "연습 횟수",
  studyTime: "오늘 연습",
  yourRhythm: "나의 리듬",
  preferences: "나에게 맞추기",
  progressIntro: "매일의 작은 연습이 차이를 만들어요.",
  collectionReward: "쌓인 연습을, 책상 위의 즐거움으로.",
  audioCredits: "오디오 크레딧",
  audioCreditsTitle: "각 키보드 축의 실제 녹음 출처",
  audioCreditsBody:
    "실제 키보드 샘플은 원본 라이선스와 함께 앱에 포함되어 오프라인으로 재생돼요.",
  audioLegacyNote:
    "Quiet Cloud는 라이선스가 확인된 저소음 녹음을 확보할 때까지 기존 KeyLingo 소리를 사용해요.",
};
